# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Gqqv14sh6Hwn4kvtEfU6K5wa-R7n-Vq
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import math

# --- Configuration & Page Setup ---
st.set_page_config(page_title="Running Decision App", page_icon="🏃", layout="centered")

# --- Load Artifacts ---
@st.cache_resource
def load_model():
    model = joblib.load('running_model.pkl')
    scaler = joblib.load('scaler.pkl')
    le = joblib.load('label_encoder.pkl')
    return model, scaler, le

model, scaler, le = load_model()

# --- Helper Functions ---
def calculate_heat_index_celsius(temp_c, humidity):
    """
    Calculate Heat Index (Feels Like) in Celsius.
    Formula based on Rothfusz regression.
    """
    if temp_c < 27 or humidity < 40:
        # Heat index is usually defined for higher temps/humidity
        return temp_c

    T = temp_c * 9/5 + 32  # Convert to Fahrenheit
    RH = humidity

    # Rothfusz equation
    HI = (-42.379 + 2.04901523*T + 10.14333127*RH - .22475541*T*RH
          - .00683783*T*T - .05481717*RH*RH + .00122874*T*T*RH
          + .00085282*T*RH*RH - .00000199*T*T*RH*RH)

    # Adjustments
    if (RH < 13 and T >= 80 and T <= 112):
        HI -= ((13-RH)/4) * math.sqrt((17-abs(T-95))/17)
    elif (RH > 85 and T >= 80 and T <= 87):
        HI += ((RH-85)/10) * ((87-T)/5)

    return (HI - 32) * 5/9  # Convert back to Celsius

def get_advice(label, hi_c):
    advice = ""
    if label == "Safe":
        advice = "สภาพอากาศดีมาก! เหมาะสำหรับการวิ่งทุกระยะทาง เตรียมตัวให้พร้อมแล้วออกไปวิ่งกันเลยครับ 🏃‍♂️"
    elif label == "Caution":
        if hi_c > 27:
            advice = "อากาศเริ่มร้อน ควรดื่มน้ำบ่อยๆ และพักผ่อนสั้นๆ ระหว่างวิ่ง 🥤"
        else:
            advice = "คุณภาพอากาศปานกลาง หากมีโรคประจำตัวเกี่ยวกับระบบหายใจ ควรใส่หน้ากากอนามัย 😷"
    elif label == "Extreme":
        advice = "เตือนภัย! สภาพอากาศเครียดมาก แนะนำให้ลดระยะเวลาการวิ่งลง หรือเปลี่ยนเป็นการออกกำลังกายในร่ม 🏠"
    elif label == "Danger":
        advice = "อันตราย! ไม่ควรออกกำลังกายกลางแจ้งเด็ดขาด ⛔ อาจเกิดอันตรายต่อสุขภาพได้ง่าย"
    return advice

def get_color_style(label):
    if label == "Safe": return "background-color: #d4edda; color: #155724; padding: 20px; border-radius: 10px; text-align: center;"
    if label == "Caution": return "background-color: #fff3cd; color: #856404; padding: 20px; border-radius: 10px; text-align: center;"
    if label == "Extreme": return "background-color: #ffeeba; color: #856404; padding: 20px; border-radius: 10px; text-align: center;"
    if label == "Danger": return "background-color: #f8d7da; color: #721c24; padding: 20px; border-radius: 10px; text-align: center;"
    return ""

# --- UI Layout ---
st.markdown("<h1 style='text-align: center; color: #2c3e50;'>🏃‍♂️ แอปพลิเคชันพิจารณาการออกไปวิ่ง</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center; color: #7f8c8d;'>ตรวจสอบความเหมาะสมของสภาพอากาศก่อนออกกำลังกาย</p>", unsafe_allow_html=True)
st.markdown("---")

with st.form("running_form"):
    col1, col2, col3 = st.columns(3)

    with col1:
        temp = st.slider("อุณหภูมิ (°C)", min_value=0, max_value=50, value=30, step=1)

    with col2:
        hum = st.slider("ความชื้น (%)", min_value=0, max_value=100, value=70, step=1)

    with col3:
        pm25 = st.slider("PM2.5 (µg/m³)", min_value=0, max_value=300, value=50, step=1)

    submitted = st.form_submit_button("ตรวจสอบเลย!")

if submitted:
    # 1. Calculate Heat Index
    feels_like = calculate_heat_index_celsius(temp, hum)

    # 2. Prepare Input for Model
    input_data = pd.DataFrame([[temp, hum, pm25]], columns=['temperature', 'humidity', 'pm25'])
    input_scaled = scaler.transform(input_data)

    # 3. Predict
    prediction_idx = model.predict(input_scaled)[0]
    label = le.inverse_transform([prediction_idx])[0]

    # 4. Display Result
    st.markdown("---")

    col_left, col_right = st.columns([1, 2])

    with col_left:
        st.metric("Feels Like", f"{feels_like:.1f} °C", "ดัชนีความร้อน")

    with col_right:
        color_style = get_color_style(label)
        st.markdown(f"<h3 style='{color_style}'>{label}</h3>", unsafe_allow_html=True)

    # 5. Advice
    advice_text = get_advice(label, feels_like)
    st.info(advice_text)

st.markdown("---")
st.caption("Developed by Senior Data Scientist | Powered by Machine Learning")